/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze/aoe2": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Aoe2
         * @description Analyze an Age of Empires II replay file.
         */
        post: operations["analyze_aoe2_api_analyze_aoe2_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze/cs2": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Cs2
         * @description Analyze a Counter-Strike 2 demo file.
         */
        post: operations["analyze_cs2_api_analyze_cs2_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/video/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Video Upload Url
         * @description Generate a signed URL for uploading a video to GCS.
         */
        post: operations["get_video_upload_url_api_video_upload_url_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/video/download-url/{object_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Video Download Url
         * @description Generate a signed URL for downloading/playing a video from GCS.
         */
        get: operations["get_video_download_url_api_video_download_url__object_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/video/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Video Models
         * @description Get list of available video analysis models.
         */
        get: operations["get_video_models_api_video_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze/video": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Video Endpoint
         * @description Analyze a gameplay video using Gemini's multimodal capabilities.
         *
         *     The video should already be uploaded to GCS (via the /api/video/upload-url flow).
         *     Optionally include a replay/demo file for richer analysis.
         *
         *     Supported game types:
         *     - aoe2: Age of Empires II (.aoe2record)
         *     - cs2: Counter-Strike 2 (.dem)
         *
         *     This endpoint:
         *     1. Downloads video from GCS
         *     2. Uploads it to Gemini File API
         *     3. Optionally parses the replay/demo for structured game data
         *     4. Analyzes with Gemini, combining video + replay data
         *     5. Returns timestamped coaching tips
         */
        post: operations["analyze_video_endpoint_api_analyze_video_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replay/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Replay Upload Url
         * @description Generate a signed URL for uploading a replay/demo file to GCS.
         */
        post: operations["get_replay_upload_url_api_replay_upload_url_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Analysis
         * @description Create and save a new analysis.
         *
         *     1. Runs video analysis (downloads from GCS, analyzes with Gemini)
         *     2. Optionally parses replay if provided
         *     3. Saves results to Firestore
         *     4. Returns shareable URL
         */
        post: operations["create_analysis_api_analysis_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/{analysis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analysis
         * @description Get a saved analysis by ID.
         */
        get: operations["get_analysis_api_analysis__analysis_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Analyses
         * @description List recent public analyses for the community carousel.
         */
        get: operations["list_analyses_api_analyses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Analysis
         * @description AI analysis results.
         */
        Analysis: {
            /** Tips */
            tips?: string[] | null;
            /** Raw Analysis */
            raw_analysis?: string | null;
            /** Model Used */
            model_used?: string | null;
            /** Provider */
            provider?: string | null;
            /** Error */
            error?: string | null;
        };
        /**
         * AnalysisDetailResponse
         * @description Full analysis data for viewing a shared analysis.
         */
        AnalysisDetailResponse: {
            /** Id */
            id: string;
            /** Game Type */
            game_type: string;
            /** Title */
            title: string;
            /** Creator Name */
            creator_name?: string | null;
            /**
             * Players
             * @default []
             */
            players: string[];
            /** Map */
            map?: string | null;
            /** Duration */
            duration?: string | null;
            /** Video Signed Url */
            video_signed_url: string;
            /** Replay Object Name */
            replay_object_name?: string | null;
            /** Thumbnail Url */
            thumbnail_url?: string | null;
            /** Tips */
            tips: components["schemas"]["TimestampedTip"][];
            /** Tips Count */
            tips_count: number;
            game_summary?: components["schemas"]["GameSummary"] | null;
            /** Model Used */
            model_used: string;
            /** Provider */
            provider: string;
            /** Created At */
            created_at: string;
        };
        /**
         * AnalysisListItem
         * @description Lightweight analysis data for carousel display.
         */
        AnalysisListItem: {
            /** Id */
            id: string;
            /** Game Type */
            game_type: string;
            /** Title */
            title: string;
            /** Creator Name */
            creator_name?: string | null;
            /** Thumbnail Url */
            thumbnail_url?: string | null;
            /** Tips Count */
            tips_count: number;
            /** Created At */
            created_at: string;
        };
        /**
         * AnalysisListResponse
         * @description Response with list of analyses.
         */
        AnalysisListResponse: {
            /** Analyses */
            analyses: components["schemas"]["AnalysisListItem"][];
            /** Total */
            total: number;
        };
        /**
         * AnalysisResponse
         * @description Response from the analyze endpoints.
         */
        AnalysisResponse: {
            /** Game Type */
            game_type: string;
            game_summary: components["schemas"]["GameSummary"];
            analysis: components["schemas"]["Analysis"];
        };
        /** Body_analyze_aoe2_api_analyze_aoe2_post */
        Body_analyze_aoe2_api_analyze_aoe2_post: {
            /**
             * Replay
             * Format: binary
             */
            replay: string;
        };
        /** Body_analyze_cs2_api_analyze_cs2_post */
        Body_analyze_cs2_api_analyze_cs2_post: {
            /**
             * Demo
             * Format: binary
             */
            demo: string;
        };
        /** Body_analyze_video_endpoint_api_analyze_video_post */
        Body_analyze_video_endpoint_api_analyze_video_post: {
            /** Video Object Name */
            video_object_name: string;
            /**
             * Replay
             * Format: binary
             */
            replay?: string;
            /** Model */
            model?: string;
            /**
             * Game Type
             * @default aoe2
             */
            game_type: string;
        };
        /**
         * GameSummary
         * @description High-level game information.
         */
        GameSummary: {
            /** Map */
            map: string;
            /** Map Size */
            map_size: string;
            /** Duration */
            duration: string;
            /** Game Version */
            game_version: string;
            /** Rated */
            rated: boolean;
            /** Players */
            players: components["schemas"]["Player"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Player
         * @description Player information from a game.
         */
        Player: {
            /** Name */
            name: string;
            /** Civilization */
            civilization: string;
            /** Color */
            color: string;
            /** Winner */
            winner: boolean;
            /** Rating */
            rating: number;
            /** Eapm */
            eapm: number;
            uptime: components["schemas"]["PlayerUptime"];
        };
        /**
         * PlayerUptime
         * @description Age advancement times in seconds.
         */
        PlayerUptime: {
            /** Feudal Age */
            feudal_age?: number | null;
            /** Castle Age */
            castle_age?: number | null;
            /** Imperial Age */
            imperial_age?: number | null;
        };
        /**
         * ReplayUploadRequest
         * @description Request to generate a signed upload URL for replay/demo files.
         */
        ReplayUploadRequest: {
            /** Filename */
            filename: string;
            /** File Size */
            file_size?: number | null;
        };
        /**
         * ReplayUploadResponse
         * @description Response with signed upload URL for replay/demo files.
         */
        ReplayUploadResponse: {
            /** Signed Url */
            signed_url: string;
            /** Object Name */
            object_name: string;
            /** Expiry Minutes */
            expiry_minutes: number;
            /** Bucket */
            bucket: string;
        };
        /**
         * SavedAnalysisRequest
         * @description Request to create and save an analysis.
         */
        SavedAnalysisRequest: {
            /** Video Object Name */
            video_object_name: string;
            /** Replay Object Name */
            replay_object_name?: string | null;
            /** Game Type */
            game_type: string;
            /** Model */
            model?: string | null;
            /** Title */
            title?: string | null;
            /** Creator Name */
            creator_name?: string | null;
            /**
             * Is Public
             * @default true
             */
            is_public: boolean;
        };
        /**
         * SavedAnalysisResponse
         * @description Response with saved analysis data and share URL.
         */
        SavedAnalysisResponse: {
            /** Id */
            id: string;
            /** Share Url */
            share_url: string;
            /** Game Type */
            game_type: string;
            /** Title */
            title: string;
            /** Creator Name */
            creator_name?: string | null;
            /**
             * Players
             * @default []
             */
            players: string[];
            /** Map */
            map?: string | null;
            /** Duration */
            duration?: string | null;
            /** Video Object Name */
            video_object_name: string;
            /** Replay Object Name */
            replay_object_name?: string | null;
            /** Thumbnail Url */
            thumbnail_url?: string | null;
            /** Tips */
            tips: components["schemas"]["TimestampedTip"][];
            /** Tips Count */
            tips_count: number;
            game_summary?: components["schemas"]["GameSummary"] | null;
            /** Model Used */
            model_used: string;
            /** Provider */
            provider: string;
            /** Created At */
            created_at: string;
        };
        /**
         * TimestampedTip
         * @description A coaching tip tied to a specific timestamp in the video.
         */
        TimestampedTip: {
            /** Timestamp Seconds */
            timestamp_seconds: number;
            /** Timestamp Display */
            timestamp_display: string;
            /** Tip */
            tip: string;
            /** Category */
            category: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VideoAnalysisResponse
         * @description Response from video analysis endpoint.
         */
        VideoAnalysisResponse: {
            /** Video Object Name */
            video_object_name: string;
            /** Duration Seconds */
            duration_seconds: number;
            /** Tips */
            tips: components["schemas"]["TimestampedTip"][];
            game_summary?: components["schemas"]["GameSummary"] | null;
            /** Model Used */
            model_used: string;
            /** Provider */
            provider: string;
            /** Error */
            error?: string | null;
        };
        /**
         * VideoDownloadResponse
         * @description Response with signed download URL.
         */
        VideoDownloadResponse: {
            /** Signed Url */
            signed_url: string;
            /** Object Name */
            object_name: string;
            /** Expiry Minutes */
            expiry_minutes: number;
        };
        /**
         * VideoUploadRequest
         * @description Request to generate a signed upload URL.
         */
        VideoUploadRequest: {
            /** Filename */
            filename: string;
            /** Content Type */
            content_type: string;
            /** File Size */
            file_size?: number | null;
        };
        /**
         * VideoUploadResponse
         * @description Response with signed upload URL.
         */
        VideoUploadResponse: {
            /** Signed Url */
            signed_url: string;
            /** Object Name */
            object_name: string;
            /** Expiry Minutes */
            expiry_minutes: number;
            /** Bucket */
            bucket: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    analyze_aoe2_api_analyze_aoe2_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_aoe2_api_analyze_aoe2_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_cs2_api_analyze_cs2_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_cs2_api_analyze_cs2_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_video_upload_url_api_video_upload_url_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VideoUploadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_video_download_url_api_video_download_url__object_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                object_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoDownloadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_video_models_api_video_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    analyze_video_endpoint_api_analyze_video_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_video_endpoint_api_analyze_video_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoAnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_replay_upload_url_api_replay_upload_url_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplayUploadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_analysis_api_analysis_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavedAnalysisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedAnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_api_analysis__analysis_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_analyses_api_analyses_get: {
        parameters: {
            query?: {
                limit?: number;
                game_type?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
